# Generated by Django 5.1.3 on 2025-12-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='monthly_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='quarterly_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='yearly_fee',
            field=models.IntegerField(default=0),
        ),
    ]
